---
title: "Canaan"
author: "Morgan Brand"
date: "29 August 2016"
output: bookdown::gitbook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pkgs, echo=FALSE}
needs(tibble)
needs(readr)
needs(tidyr)
needs(dplyr)
needs(ggplot2)
needs(magrittr)
needs(forcats)
needs(knitr)
needs(sm)
needs(sjPlot)
needs(HH)
needs(broom)
needs(plotly)
needs(gridExtra)
needs(nlme)
needs(lubridate)
```

# Production

The farm has a combination of sugar cane and bananas. Some of the banana fields have been replanted to cane in the past few years. The fields currently in production are 1011, 101, and a newly combined 96 (old 93 + 96). Data from 2008 has been captured and will be presented in the following section.

```{r, echo=FALSE}
production <- read_csv("Banana Production.csv")
glimpse(production)
dat<-production %>%
  select(1:12) %>%
  mutate(date = parse_date_time(Date,"%d-%m-%Y")) %>%
  mutate(Field = stringr::str_replace(Field, "93", "f93"),
         Field = stringr::str_replace(Field, "96", "f96"),
         Field = stringr::str_replace(Field, "101", "f101"),
         Field = stringr::str_replace(Field, "1011", "f1011"),
         Field = stringr::str_replace(Field, "102", "f102"))

dat$y<-year(dat$date)
dat$m<-month(dat$date)

dat<-dat %>%
  mutate(y=as.factor(y),
         m=as.factor(m))
write_csv(dat, "production_by_y.csv")
```

```{r}
#old field size
old.size <- 
  dat %>%
  filter(y >= "2008", y<="2014") %>%
  group_by(y, m, Field) %>%
  dplyr::summarise(cum.sum = sum(weight)) 


new.size <- 
  dat %>%
  filter(date >= "2015-01-01", date<="2016-08-16") %>%
  group_by(y, m, Field) %>%
  dplyr::summarise(cum.sum = sum(weight))


all<-full_join(old.size, new.size)
all<-all %>%
  ungroup(y,m) %>%
  mutate(y=as.factor(y),
         m=as.factor(m))

n<-ggplot(all, aes(y, cum.sum, fill = Field)) +
  #geom_point(aes(color = animal)) +
  #geom_line(aes(colour = y)) 
  #geom_smooth(span = 0.5) +
  geom_bar(stat = "identity", position = "dodge") 
  #facet_wrap(~Field) 
ggplotly(n)

#  mutate(he93 = f93 /1.51,
#         he96 = f96 /1.31,
#         he101 = f101/2.07,
#         he1011 = ff1011/2.21,
#         he102 = f102/1.12) 
```


```{r}
#old field size
old.size.y <- 
  dat %>%
  filter(y >= "2008", y<="2014") %>%
  group_by(y, Field) %>%
  dplyr::summarise(cum.sum = sum(weight)) 


new.size.y <- 
  dat %>%
  filter(y >= "2015", y<="2016") %>%
  group_by(y, Field) %>%
  dplyr::summarise(cum.sum = sum(weight))

  

all<-full_join(old.size.y, new.size.y)
all<-all %>%
  ungroup(y,Field) %>%
  mutate(y=as.factor(y),
         m=as.factor(Field),
         Field=as.factor(Field))

```

This containes production per hectare for each field

```{r}

tonnage <- dat %>%
  group_by(Field, y) %>%
  dplyr::summarise(year.sum = sum(weight)) 

#calculating tonnage per hectare
tonnage.old <- tonnage %>%
  filter(y >= "2008", y<="2014") %>%
  spread(key = Field, value = year.sum) %>%
  group_by(y) %>%
  mutate(he93 = f93 /1.51,
         he96 = f96 /1.31,
         he101 = f101/2.07,
         he1011 = ff1011/2.21,
         he102 = f102/1.12) %>%
  select(y, he93, he96, he101, he1011, he102) %>%
  gather(field, tonnage, 2:6)

ggplot(tonnage.old, aes(y=tonnage, x=y, fill=field)) +
  geom_bar(stat="Identity", position = "dodge")
#in 2015 93 and 96 merged which will effect the 2015 2016 tonnage
tonnage.new <- tonnage %>%
  filter(y >= "2015", y<="2016") %>%
  spread(key = Field, value = year.sum) %>%
  group_by(y) %>%
  mutate(he93 = f93 /0.74,
         he96 = f96 /2.09,
         he101 = f101/2.07,
         he1011 = ff1011/2.21,
         he102 = f102/1.12) %>% 
  select(date, y, he93, he96, he101, he1011, he102) %>%
  gather(field, tonnage, 3:7)

a<-full_join(tonnage.old, tonnage.new)
a <- a %>%
ungroup(y,field) %>%
  mutate(y=as.factor(y),
         field=as.factor(field))

n<-ggplot(a, aes(y, tonnage, fill = y)) +
  #geom_point()+
  #geom_line() +
  #geom_smooth(span = 0.5) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~field, ncol = 1) +
  theme_bw() +
  scale_y_continuous(limits=c(0,26000), breaks=seq(0,25000, by = 5000)) +
  labs(x = "Year",
       y = "Tonnes per hectare")
ggplotly(n)
n
ggsave("production.pdf", n,
       width = 6, height = 12)

```

