---
title: "Canaan Rainin"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
    #storyboard: true
---

```{r pkgs}
needs(tibble)
needs(readr)
needs(tidyr)
needs(dplyr)
needs(ggplot2)
needs(magrittr)
needs(forcats)
needs(knitr)
needs(sm)
needs(sjPlot)
needs(HH)
needs(broom)
needs(plotly)
needs(gridExtra)
needs(nlme)
needs(lubridate)
needs(zoo)
needs(moments)
needs(dygraphs)
```

```{r setup, include=FALSE}
library(flexdashboard)
load("rainfall.Rdata")
rainfall<- rainfall %>%
  mutate(month = as.factor(month))
  
print(levels(rainfall$month)) 
rainfall$month = factor(rainfall$month,levels(rainfall$month)[c(5,4,8,1,9,7,6,2,12,11,10,3)])

```

Each of these plots are dynamic and can be zoomed in on. Hover the cursor over the area of interest to see the values and select a range of interest.

Column {data-width=950}
-----------------------------------------------------------------------

### Rain by month with smooth

```{r rainbymonth, fig.cap="Monthly rainfall for the period 1908 - 2016 with a line of best fit and 95 % confidence interval."}
month <-
  ggplot(rainfall, aes(y=rain_mm, x=Date, fill = month)) +
  geom_bar(stat = "identity") +
  geom_smooth(method = loess) +
  facet_grid(~ month) +
  theme_bw() +
  scale_y_continuous(limits=c(0,350), breaks=seq(0,350, by = 500)) +
  scale_x_date(date_breaks = "40 years", date_labels = "%Y") +
  labs(x = "Year",
       y = "Monthly rainfall (mm)") +
  theme(legend.position="none")

ggplotly(month)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Annual rainfall

```{r, fig.cap="Annual rainfall for the period 1908 - 2016 with a line of best fit and 95 % confidence interval."}
year <-
  ggplot(rainfall, aes(y=total.y, x=Date)) +
  geom_bar(stat = "identity") +
  geom_smooth(method = "loess", span = 0.2, colour="black", fill="limegreen") +
  theme(legend.position="none", legend.key = element_blank()) +
  theme_bw() +
  #facet_grid(~ month) +
  #scale_y_continuous(limits=c(0,350), breaks=seq(0,350, by = 500)) +
  scale_x_date(date_breaks = "10 years", date_labels = "%Y") +
  labs(x = "Year",
       y = "Annual rainfall (mm)")

ggplotly(year)
```

### Monthly means

```{r, fig.cap="Mean monthly rainfall for the period 1908 - 2016 with standard deveation denoted by the error bars"}
rainfall_m <- 
  rainfall %>%
  na.omit() %>%
  group_by(month) %>%
  summarise(mean_month = mean(rain_mm),
            sd = sd(rain_mm))

month_mean<-
  ggplot(rainfall_m, aes(y=mean_month, x=month, fill = month)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin=mean_month-sd, ymax=mean_month+sd), width=.1) +
  #geom_smooth(method = "loess", span = 0.2, colour="black", fill="limegreen") +
  theme_bw() +
  guides(fill=FALSE) +
  #facet_grid(~ month) +
  #scale_y_continuous(limits=c(0,350), breaks=seq(0,350, by = 500)) +
  #scale_x_date(date_breaks = "10 years", date_labels = "%Y") +
  labs(x = "Month",
       y = "Mean monthly rainfall (mm)") +
  theme(legend.position="none")

ggplotly(month_mean)
```

